# Generated by Django 5.2.7 on 2025-12-05 04:14

from django.db import migrations
import os

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    
    # Create superuser if it doesn't exist
    if not User.objects.filter(username='Babb').exists():
        User.objects.create_superuser(
            username='Babb',
            password='Babb123'
        )
        print("Superuser created successfully!")

class Migration(migrations.Migration):
    dependencies = [
        ('blog', '0003_post_author_post_image_alter_blogpost_author'),
    ]
    
    operations = [
        migrations.RunPython(create_superuser),
    ]

