# Generated by Django 5.2.7 on 2025-12-05 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_create_admin_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post'),
        ),
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
    ]
